### ISSUE TITLE
Is possible to turn Vector3 fields into public fields ?

### ISSUE THREAD

**Issue by gabrielhamel** [dacite/wot-battle-results-parser#6]
```rust
pub struct Vector3 {
    x: f32,
    z: f32,
    y: f32,
}
```
I can't retrieve them, or i need to serialize them in json before (I don't think it's a good way ^^)

**Comment by dacite** [comment]
That's an oversight on my part. I will make the fields public

**Comment by gabrielhamel** [comment]
Nice thank you
